//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace MVCHomeWork01.Models
{
    using System;
    using System.Collections.Generic;

    public partial class 客戶聯絡人
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public int 客戶Id { get; set; }

        [Required]
        [MaxLength(50)]
        public string 職稱 { get; set; }

        [Required]
        [MaxLength(50)]
        public string 姓名 { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [MaxLength(250)]
        public string Email { get; set; }

        [MaxLength(50)]
        public string 手機 { get; set; }

        [MaxLength(50)]
        public string 電話 { get; set; }

        public bool 是否已刪除 { get; set; }

        public virtual 客戶資料 客戶資料 { get; set; }
    }
}
